In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('coursea_data.csv')

In [4]:
df

,ID,course,course_organization,Certificate_type,rating,difficulty,students_enrolled
0,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5.3k
1,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17k
2,874,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130k
3,413,A Law Student's Toolkit,Yale University,COURSE,4.7,Mixed,91k
4,635,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,4.8,Mixed,320k
...,...,...,...,...,...,...,...
886,236,Программирование на Python,Mail.Ru Group,SPECIALIZATION,4.5,Intermediate,52k
887,883,Психолингвистика (Psycholinguistics),Saint Petersburg State University,COURSE,4.8,Mixed,21k
888,545,Разработка интерфейсов: вёрстка и JavaScript,E-Learning Development Fund,SPECIALIZATION,4.5,Intermediate,30k
889,875,Русский как иностранный,Saint Petersburg State University,SPECIALIZATION,4.6,Intermediate,9.8k
890,163,Финансовые инструменты для частного инвестора,National Research University Higher School of ...,SPECIALIZATION,4.7,Beginner,38k

In [5]:
print(df.dtypes)

ID                       int64
course                  object
course_organization     object
Certificate_type        object
rating                 float64
difficulty              object
students_enrolled       object
dtype: object

In [6]:
#replacing k with 000
def transform(co):
    data=co.split(",")
    transformed_data=[]
    for i in data:
        if "k" in i:
            i=i.replace("k","")
            i=float(i)*1000
        transformed_data.append(i)
    return",".join([str(elem) for elem in transformed_data])

In [7]:
df["students_enrolled"]=df["students_enrolled"].apply(transform)
df

,ID,course,course_organization,Certificate_type,rating,difficulty,students_enrolled
0,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5300.0
1,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17000.0
2,874,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130000.0
3,413,A Law Student's Toolkit,Yale University,COURSE,4.7,Mixed,91000.0
4,635,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,4.8,Mixed,320000.0
...,...,...,...,...,...,...,...
886,236,Программирование на Python,Mail.Ru Group,SPECIALIZATION,4.5,Intermediate,52000.0
887,883,Психолингвистика (Psycholinguistics),Saint Petersburg State University,COURSE,4.8,Mixed,21000.0
888,545,Разработка интерфейсов: вёрстка и JavaScript,E-Learning Development Fund,SPECIALIZATION,4.5,Intermediate,30000.0
889,875,Русский как иностранный,Saint Petersburg State University,SPECIALIZATION,4.6,Intermediate,9800.0
890,163,Финансовые инструменты для частного инвестора,National Research University Higher School of ...,SPECIALIZATION,4.7,Beginner,38000.0

In [8]:
#replacing m with 000000
def transform(co):
    data=co.split(",")
    transformed_data=[]
    for i in data:
        if "m" in i:
            i=i.replace("m","")
            i=float(i)*1000000
        transformed_data.append(i)
    return",".join([str(elem) for elem in transformed_data])

In [9]:
df["students_enrolled"]=df["students_enrolled"].apply(transform)
df

,ID,course,course_organization,Certificate_type,rating,difficulty,students_enrolled
0,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5300.0
1,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17000.0
2,874,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130000.0
3,413,A Law Student's Toolkit,Yale University,COURSE,4.7,Mixed,91000.0
4,635,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,4.8,Mixed,320000.0
...,...,...,...,...,...,...,...
886,236,Программирование на Python,Mail.Ru Group,SPECIALIZATION,4.5,Intermediate,52000.0
887,883,Психолингвистика (Psycholinguistics),Saint Petersburg State University,COURSE,4.8,Mixed,21000.0
888,545,Разработка интерфейсов: вёрстка и JavaScript,E-Learning Development Fund,SPECIALIZATION,4.5,Intermediate,30000.0
889,875,Русский как иностранный,Saint Petersburg State University,SPECIALIZATION,4.6,Intermediate,9800.0
890,163,Финансовые инструменты для частного инвестора,National Research University Higher School of ...,SPECIALIZATION,4.7,Beginner,38000.0

In [10]:
df.loc[df['students_enrolled']=='3.2m']

Empty DataFrame
Columns: [ID, course, course_organization, Certificate_type, rating, difficulty, students_enrolled]
Index: []

In [11]:
print(df.dtypes)

ID                       int64
course                  object
course_organization     object
Certificate_type        object
rating                 float64
difficulty              object
students_enrolled       object
dtype: object

In [12]:
#typecasting object to integer
df["students_enrolled"]=pd.to_numeric(df["students_enrolled"], downcast='integer')

In [13]:
print(df.dtypes)

ID                       int64
course                  object
course_organization     object
Certificate_type        object
rating                 float64
difficulty              object
students_enrolled        int32
dtype: object

In [14]:
#rounding the Rating column
df.round({"rating":1})

,ID,course,course_organization,Certificate_type,rating,difficulty,students_enrolled
0,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5300
1,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17000
2,874,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130000
3,413,A Law Student's Toolkit,Yale University,COURSE,4.7,Mixed,91000
4,635,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,4.8,Mixed,320000
...,...,...,...,...,...,...,...
886,236,Программирование на Python,Mail.Ru Group,SPECIALIZATION,4.5,Intermediate,52000
887,883,Психолингвистика (Psycholinguistics),Saint Petersburg State University,COURSE,4.8,Mixed,21000
888,545,Разработка интерфейсов: вёрстка и JavaScript,E-Learning Development Fund,SPECIALIZATION,4.5,Intermediate,30000
889,875,Русский как иностранный,Saint Petersburg State University,SPECIALIZATION,4.6,Intermediate,9800
890,163,Финансовые инструменты для частного инвестора,National Research University Higher School of ...,SPECIALIZATION,4.7,Beginner,38000

In [15]:
#approximating the rating data
df.loc[(df['rating'] >= 1) & (df['rating'] <= 1.3), 'revised_rating'] = 1
df.loc[(df['rating'] >= 1.4) & (df['rating'] <= 1.7), 'revised_rating'] = 1.5
df.loc[(df['rating'] >= 1.8) & (df['rating'] <= 2.3), 'revised_rating'] = 2
df.loc[(df['rating'] >= 2.4) & (df['rating'] <= 2.7), 'revised_rating'] = 2.5
df.loc[(df['rating'] >= 2.8) & (df['rating'] <= 3.3), 'revised_rating'] = 3
df.loc[(df['rating'] >= 3.4) & (df['rating'] <= 3.7), 'revised_rating'] = 3.5
df.loc[(df['rating'] >= 3.8) & (df['rating'] <= 4.3), 'revised_rating'] = 4
df.loc[(df['rating'] >= 4.4) & (df['rating'] <= 4.7), 'revised_rating'] = 4.5
df.loc[(df['rating'] >= 4.8) & (df['rating'] <= 5), 'revised_rating'] = 5

In [16]:
df

,ID,course,course_organization,Certificate_type,rating,difficulty,students_enrolled,revised_rating
0,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5300,4.5
1,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17000,4.5
2,874,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130000,4.5
3,413,A Law Student's Toolkit,Yale University,COURSE,4.7,Mixed,91000,4.5
4,635,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,4.8,Mixed,320000,5.0
...,...,...,...,...,...,...,...,...
886,236,Программирование на Python,Mail.Ru Group,SPECIALIZATION,4.5,Intermediate,52000,4.5
887,883,Психолингвистика (Psycholinguistics),Saint Petersburg State University,COURSE,4.8,Mixed,21000,5.0
888,545,Разработка интерфейсов: вёрстка и JavaScript,E-Learning Development Fund,SPECIALIZATION,4.5,Intermediate,30000,4.5
889,875,Русский как иностранный,Saint Petersburg State University,SPECIALIZATION,4.6,Intermediate,9800,4.5
890,163,Финансовые инструменты для частного инвестора,National Research University Higher School of ...,SPECIALIZATION,4.7,Beginner,38000,4.5

In [17]:
print(df.dtypes)

ID                       int64
course                  object
course_organization     object
Certificate_type        object
rating                 float64
difficulty              object
students_enrolled        int32
revised_rating         float64
dtype: object

In [17]:
#for visulaizaton purpose
#duplicating each row for once
newdf = pd.DataFrame(np.repeat(df.values,2,axis=0))
newdf.columns = df.columns
print(newdf)

       ID                                             course  \
0     134  (ISC)² Systems Security Certified Practitioner...
1     134  (ISC)² Systems Security Certified Practitioner...
2     743  A Crash Course in Causality:  Inferring Causal...
3     743  A Crash Course in Causality:  Inferring Causal...
4     874                     A Crash Course in Data Science
...   ...                                                ...
1777  545       Разработка интерфейсов: вёрстка и JavaScript
1778  875                            Русский как иностранный
1779  875                            Русский как иностранный
1780  163      Финансовые инструменты для частного инвестора
1781  163      Финансовые инструменты для частного инвестора

                                    course_organization Certificate_type  \
0                                                (ISC)²   SPECIALIZATION
1                                                (ISC)²   SPECIALIZATION
2                            University of Pennsylvania           COURSE
3                            University of Pennsylvania           COURSE
4                              Johns Hopkins University           COURSE
...                                                 ...              ...
1777                        E-Learning Development Fund   SPECIALIZATION
1778                  Saint Petersburg State University   SPECIALIZATION
1779                  Saint Petersburg State University   SPECIALIZATION
1780  National Research University Higher School of ...   SPECIALIZATION
1781  National Research University Higher School of ...   SPECIALIZATION

     rating    difficulty students_enrolled revised_rating
0       4.7      Beginner              5300            4.5
1       4.7      Beginner              5300            4.5
2       4.7  Intermediate             17000            4.5
3       4.7  Intermediate             17000            4.5
4       4.5         Mixed            130000            4.5
...     ...           ...               ...            ...
1777    4.5  Intermediate             30000            4.5
1778    4.6  Intermediate              9800            4.5
1779    4.6  Intermediate              9800            4.5
1780    4.7      Beginner             38000            4.5
1781    4.7      Beginner             38000            4.5

[1782 rows x 8 columns]

In [20]:
#adding a new column - path with each row to be 1 or 5 based on its index
newdf.loc[newdf.index%2 == 0, 'path'] = 1
newdf.loc[newdf.index%2 != 0, 'path'] = 5

In [21]:
newdf.head()

,ID,course,course_organization,Certificate_type,rating,difficulty,students_enrolled,revised_rating,path
0,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5300,4.5,1.0
1,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5300,4.5,5.0
2,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17000,4.5,1.0
3,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17000,4.5,5.0
4,874,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130000,4.5,1.0

In [23]:
#typecsting path column to integer
newdf["path"]=pd.to_numeric(newdf["path"], downcast='integer')
newdf

,ID,course,course_organization,Certificate_type,rating,difficulty,students_enrolled,revised_rating,path
0,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5300,4.5,1
1,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5300,4.5,5
2,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17000,4.5,1
3,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17000,4.5,5
4,874,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130000,4.5,1
...,...,...,...,...,...,...,...,...,...
1777,545,Разработка интерфейсов: вёрстка и JavaScript,E-Learning Development Fund,SPECIALIZATION,4.5,Intermediate,30000,4.5,5
1778,875,Русский как иностранный,Saint Petersburg State University,SPECIALIZATION,4.6,Intermediate,9800,4.5,1
1779,875,Русский как иностранный,Saint Petersburg State University,SPECIALIZATION,4.6,Intermediate,9800,4.5,5
1780,163,Финансовые инструменты для частного инвестора,National Research University Higher School of ...,SPECIALIZATION,4.7,Beginner,38000,4.5,1
1781,163,Финансовые инструменты для частного инвестора,National Research University Higher School of ...,SPECIALIZATION,4.7,Beginner,38000,4.5,5

In [24]:
#exporting new dataframe to a csv file
newdf.to_excel (r'D:\Tableau\Datasets\export_Coursera.xlsx', index = False, header=True)